# Generated by Django 4.1.1 on 2022-11-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='usuario',
        ),
    ]
