# Generated by Django 4.1.1 on 2022-11-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_email_login_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
