# Generated by Django 4.1.1 on 2022-11-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrar',
            name='email2',
        ),
    ]
