# Generated by Django 4.1.1 on 2023-01-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_cadastrar_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrar',
            name='email',
            field=models.CharField(default='email@technobox.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='cadastrar',
            name='confirmasenha',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastrar',
            name='senha2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastrar',
            name='usuario2',
            field=models.CharField(max_length=15),
        ),
    ]
