# Generated by Django 4.1.1 on 2022-10-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdntv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=26)),
                ('senha', models.CharField(max_length=25)),
                ('edge', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=300)),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
    ]
