# Generated by Django 4.1.1 on 2022-11-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdntv',
            name='demandinha',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='cdntv',
            name='provedor',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='cdntv',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
