# Generated by Django 4.1.1 on 2022-11-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cdntv_demandinha_cdntv_provedor_alter_cdntv_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdntv',
            name='demandinha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cdntv',
            name='provedor',
            field=models.CharField(max_length=50),
        ),
    ]
