# Generated by Django 4.1.1 on 2022-11-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cdntv_demandinha_alter_cdntv_provedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdntv',
            name='demandinha',
        ),
        migrations.RemoveField(
            model_name='cdntv',
            name='provedor',
        ),
    ]
