# Generated by Django 4.1.1 on 2022-12-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aplicativos_self_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origindown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin4', models.CharField(max_length=30)),
                ('email4', models.CharField(max_length=30)),
                ('ndemanda4', models.CharField(max_length=30)),
                ('nprovdor4', models.CharField(max_length=20)),
            ],
        ),
    ]
