# Generated by Django 4.1.1 on 2023-01-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_origindown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downedge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin5', models.CharField(max_length=30)),
                ('email5', models.CharField(max_length=30)),
                ('ndemanda5', models.CharField(max_length=30)),
                ('nprovdor5', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Downedgevod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge8', models.CharField(max_length=30)),
                ('vod2', models.CharField(max_length=30)),
                ('email8', models.CharField(max_length=30)),
                ('ndemanda8', models.CharField(max_length=30)),
                ('nprovdor8', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Downoriginedgevod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin7', models.CharField(max_length=30)),
                ('edge9', models.CharField(max_length=30)),
                ('vod3', models.CharField(max_length=30)),
                ('email9', models.CharField(max_length=30)),
                ('ndemanda9', models.CharField(max_length=30)),
                ('nprovedor9', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Downoriginvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin6', models.CharField(max_length=30)),
                ('vod1', models.CharField(max_length=30)),
                ('email7', models.CharField(max_length=30)),
                ('ndemanda7', models.CharField(max_length=30)),
                ('nprovdor7', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Downvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vod', models.CharField(max_length=30)),
                ('email6', models.CharField(max_length=30)),
                ('ndemanda6', models.CharField(max_length=30)),
                ('nprovdor6', models.CharField(max_length=20)),
            ],
        ),
    ]
