# Generated by Django 4.1.1 on 2023-01-15 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_downedge_downedgevod_downoriginedgevod_downoriginvod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='origindown',
            old_name='nprovdor4',
            new_name='nprovedor4',
        ),
    ]
