# Generated by Django 4.1.1 on 2023-01-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_nprovdor4_origindown_nprovedor4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origindown',
            name='nprovedor4',
            field=models.CharField(default='Valor', max_length=20),
        ),
    ]
