# Generated by Django 4.1.1 on 2023-01-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_origindown_nprovedor4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downedge',
            old_name='origin5',
            new_name='edge5',
        ),
        migrations.RenameField(
            model_name='downedge',
            old_name='nprovdor5',
            new_name='nprovedor5',
        ),
        migrations.AlterField(
            model_name='origindown',
            name='nprovedor4',
            field=models.CharField(default='PROVEDOR', max_length=30),
        ),
    ]
