# Generated by Django 4.1.1 on 2023-01-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_origin5_downedge_edge5_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downvod',
            old_name='nprovdor6',
            new_name='nprovedor6',
        ),
    ]
