# Generated by Django 4.1.1 on 2023-01-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_nprovdor6_downvod_nprovedor6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downoriginvod',
            old_name='nprovdor7',
            new_name='nprovedor7',
        ),
    ]
