# Generated by Django 4.1.1 on 2023-01-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_nprovdor7_downoriginvod_nprovedor7'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downoriginvod',
            old_name='origin6',
            new_name='origin8',
        ),
    ]
