# Generated by Django 4.1.1 on 2023-01-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_nprovdor8_downedgevod_nprovedor8_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicativos',
            name='email3',
            field=models.EmailField(max_length=62),
        ),
        migrations.AlterField(
            model_name='downedge',
            name='email5',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='downoriginvod',
            name='email7',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='downoriginvod',
            name='origin8',
            field=models.CharField(default='Origin', max_length=30),
        ),
        migrations.AlterField(
            model_name='downvod',
            name='email6',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='origindown',
            name='email4',
            field=models.EmailField(max_length=30),
        ),
    ]
